### ISSUE TITLE
Some problems about the experiments.

### ISSUE THREAD

**Issue by mbs0221** [gingsmith/fmtl#1]
Currently, I want to run grid-search and cross-validation on your code, but I did not know how to adjust those parameters. Would you please provide some suggestions here about parameter selection? Thank you!

**Comment by gingsmith** [comment]
The regularization hyperparameter space can be set in the model_driver.m script [through the variable `lambda_range`]. The rest of the hyperparameters (related to the various optimization methods) can be set using the `opt` struct -- you can find examples in model_driver.m and optimization_driver.m.
