### ISSUE TITLE
Possible typo in Primal objective function calculation

### ISSUE THREAD

**Issue by kudhru** [gingsmith/fmtl#2]
https://github.com/gingsmith/fmtl/blob/b27ccee9eca68074f59877fc7d073ffb5b352b38/opt/simple_svm.m#L37

Hi 

Should the above be 
`primal_new = mean(max(0.0, 1.0 - preds)) + lambda * (w' * w);` 
instead?

**Comment by gingsmith** [comment]
You're correct--this was copied incorrectly for the code release. Thanks for catching it!

**Comment by kudhru** [comment]
Thanks!

**Comment by kudhru** [comment]
Also, should it be `lambda/2` or `lambda` in the regularizer term (second term) above?
