### ISSUE TITLE
Primal and Dual function definitions

### ISSUE THREAD

**Issue by kudhru** [gingsmith/fmtl#3]
Hi

Are the [Primal](https://github.com/gingsmith/fmtl/blob/master/util/compute_primal.m) and [Dual](https://github.com/gingsmith/fmtl/blob/master/util/compute_dual.m) functions used for Mocha implementation, same as those mentioned in the [paper](https://www.cs.cmu.edu/~atalwalk/flearn_nips.pdf) (Equation 1 and Equation 3) ? I was wondering if the L2 regularization term is missing in the code as mentioned in the MTL regularizer (Equation 2 in the paper). 

Thanks
Dhruv

**Comment by gingsmith** [comment]
We didn't find that the extra regularization term on W made a significant difference, and so we omitted this from the code. However it could be easily incorporated by setting Omega = Omega_old + (lambda_2 / lambda_1) * I_(m x m).
